
title: InvenTree
tagline: Intuitive Inventory Management
demo-link: https://demo.inventreedb.com/
doc-link: https://inventree.readthedocs.io/en/latest/
plugin-link: https://repo.invenhost.com/

description: >-
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

baseurl: "/home.invenhost.com"
url: """


plugins:
  - jekyll-seo-tag
  - jekyll-postcss

exclude: [
  styles/index.css,
  styles/syntax.css,
  package.json,
  package-lock.json,
  postcss.config.js,
  readme.md,
]