
title: InvenTree
tagline: Intuitive Inventory Management
demo-link: https://inventree.readthedocs.io/en/latest/demo/
doc-link: https://inventree.readthedocs.io/en/latest/
plugin-link: https://repo.invenhost.com/

description: >-
  InvenTree is an open-source inventory management system which provides intuitive parts management and stock control.
  It is at the center of an ecosystem of addins for EDA tools, API wrapper, deeply integrated plugins and 3rd party tools.

baseurl: "/home.invenhost.com"
url: ""

collections:
  publishers:
    output: true
    permalink: "/:title"
  plugins:
    output: true
    custom_permalink_placeholders: ["publisher"]
    #permalink: "/:publisher/:title"

defaults:
  - scope:
      path: ""
      type: "publishers"
    values:
      layout: "publisher"
  - scope:
      path: ""
      type: "plugins"
    values:
      layout: "plugin"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-seo-tag
  - jekyll-postcss-v2
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-mentions
  - jekyll_custom_permalink

exclude: [
  package.json,
  package-lock.json,
  postcss.config.js,
  README.md,
  tailwind.config.js,
  LICENSE,
]
