
title: InvenTree
description: Intuitive Inventory Management
demo-link: http://demo.inventreedb.com/

plugins:
  - jekyll-seo-tag

exclude: [
  styles/index.css,
  styles/syntax.css,
  package.json,
  package-lock.json,
  postcss.config.js,
  readme.md,
]