
title: InvenTree
tagline: Intuitive Inventory Management
demo-link: http://demo.inventreedb.com/
doc-link: https://inventree.readthedocs.io/en/latest/
plugin-link: https://repo.invenhost.com/

description: >-
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com


plugins:
  - jekyll-seo-tag

exclude: [
  styles/index.css,
  styles/syntax.css,
  package.json,
  package-lock.json,
  postcss.config.js,
  readme.md,
]