name: Get stats

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set selected color
        run: python .github/get_stats.py
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "[Bot] Updated the stats"
          branch: main
